sudo: false
language: python
os:
  - linux
matrix:
  include:
    - python: 3.5
      env:
        - TOXENV=py35
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 3.7
      dist: xenial
      env:
        - TOXENV=py37
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox